//! In-box `sshd` for `kern box --ssh` - a throwaway SSH server so you can `ssh` (and `scp`/`sftp`)
//! into a running box. Runs entirely inside the box's namespaces and is torn down with it.
//!
//! This has to happen **in the isolation layer, before seccomp**: making `sshd` work rootless needs
//! privileged setup the workload itself can't do (the seccomp filter blocks `mount`) -
//!   * a fresh `tmpfs` on `/run` so `/run/sshd` is owned by the namespace root and passes sshd's
//!     privsep ownership check (a host-owned `/run/sshd` shows up as `nobody` and sshd refuses it);
//!   * a bind-mounted `/etc/passwd`/`/etc/shadow` giving sshd's privilege-separation user UID 0, so
//!     its `setresuid` privsep drop is a no-op in a single-uid user namespace;
//!   * an LD_PRELOAD shim that stubs `setgroups`/`initgroups` (they return `EPERM` under
//!     `/proc/self/setgroups=deny`, which sshd treats as fatal - clearing the single mapped group is
//!     a no-op anyway).
//!
//! Keys never touch the image: the host key + `authorized_keys` + config live on the `/run` tmpfs.
//! sshd binds `127.0.0.1:22` inside the box's own network namespace; the caller wires the host port
//! to it with the ordinary `-p HOST:22` rootless forwarder. sshd is `fork`ed as a child just before
//! the box execs its PID 1, so it dies with the box's PID namespace.
//!
//! Honest scope: the box must ship `sshd` + `ssh-keygen` (openssh-server). The forked sshd - and the
//! shells it spawns per session - run **without** the box's seccomp filter (they're forked before it
//! is installed); the namespace/pivot/cgroup isolation still holds. Grant `--ssh` to workloads you'd
//! trust with an interactive shell in the box.

use std::ffi::CString;
use std::io::Write;
use std::path::Path;

/// What the box needs to stand up sshd: the tenant's public key (its `authorized_keys`).
pub struct SshSetup {
    /// The single public key allowed to log in (from `--ssh-key`, or generated by the CLI).
    pub authorized_key: String,
}

const SSH_DIR: &str = "/run/kern-ssh";
const HOST_KEY: &str = "/run/kern-ssh/hostkey";
const AUTH_KEYS: &str = "/run/kern-ssh/authorized_keys";
const CONFIG: &str = "/run/kern-ssh/sshd_config";
const PASSWD: &str = "/run/kern-ssh/passwd";
const SHADOW: &str = "/run/kern-ssh/shadow";
const SHIM: &str = "/run/kern-ssh/nogroups.so";

fn cs(s: &str) -> Option<CString> {
    CString::new(s).ok()
}

/// Stand up sshd inside the box. Best-effort: any failure warns and leaves the box running without
/// SSH rather than aborting it. Must run after the loopback is up and before seccomp is installed.
pub fn setup(ssh: &SshSetup) {
    // The box-owned tmpfs over `/run` is already mounted by the caller (before pivot), so `/run/sshd`
    // is namespace-root-owned (sshd's privsep ownership check) and our key material lives off the
    // image. Here we just create the dirs and files on it.
    for (d, mode) in [
        ("/run/sshd", 0o755),
        ("/var/empty", 0o755),
        (SSH_DIR, 0o700),
    ] {
        let _ = std::fs::create_dir_all(d);
        set_mode(d, mode);
    }

    // 2. Host key (ed25519 - fast + tiny). ssh-keygen writes it 0600.
    let keygen = std::process::Command::new("ssh-keygen")
        .args(["-t", "ed25519", "-f", HOST_KEY, "-N", "", "-q"])
        .status();
    if !matches!(keygen, Ok(s) if s.success()) {
        warn("ssh-keygen failed (is openssh installed in the image?) - SSH not started");
        return;
    }

    // 3. authorized_keys (0600).
    if write_mode(AUTH_KEYS, ssh.authorized_key.trim().as_bytes(), 0o600).is_err() {
        warn("cannot write authorized_keys - SSH not started");
        return;
    }

    // 4. passwd/shadow with the privsep user `sshd` (and `root`) at UID 0, bind-mounted over the
    //    image's - never modifying the image. UID 0 makes sshd's privsep `setresuid` a no-op in a
    //    single-uid namespace; `root` gets a writable home so the login shell can chdir.
    let _ = std::fs::create_dir_all("/tmp/kern-home");
    set_mode("/tmp/kern-home", 0o700);
    let passwd = "root:x:0:0:root:/tmp/kern-home:/bin/sh\n\
                  sshd:x:0:0:sshd privsep:/var/empty:/sbin/nologin\n";
    let shadow = "root:*:19764:0:99999:7:::\nsshd:*:19764:0:99999:7:::\n";
    if write_mode(PASSWD, passwd.as_bytes(), 0o644).is_ok() {
        bind_over(PASSWD, "/etc/passwd");
    }
    if write_mode(SHADOW, shadow.as_bytes(), 0o640).is_ok() {
        bind_over(SHADOW, "/etc/shadow");
    }

    // 5. The setgroups/initgroups shim (see module docs). Compiled into the box only if a C compiler
    //    is present; without it sshd still starts but a login may fail at privsep on a single-uid box
    //    (use `--uid-range`, which maps groups so setgroups succeeds, or install cc). Best-effort.
    let preload = build_shim();

    // 6. sshd_config - pubkey-only, no PAM/password, fast single cipher suite, no DNS.
    let sftp = [
        "/usr/lib/openssh/sftp-server",
        "/usr/lib/ssh/sftp-server",
        "/usr/libexec/openssh/sftp-server",
        "/usr/libexec/sftp-server",
    ]
    .into_iter()
    .find(|p| Path::new(p).exists())
    .unwrap_or("");
    let mut cfg = String::from(
        "Port 22\nListenAddress 127.0.0.1\nHostKey /run/kern-ssh/hostkey\n\
         AuthorizedKeysFile /run/kern-ssh/authorized_keys\nPermitRootLogin yes\n\
         PasswordAuthentication no\nKbdInteractiveAuthentication no\nUsePAM no\n\
         PermitEmptyPasswords no\nX11Forwarding no\nAllowAgentForwarding no\nPrintMotd no\n\
         AllowTcpForwarding no\nPermitTunnel no\nGatewayPorts no\n\
         StrictModes no\nUseDNS no\nLogLevel ERROR\nPidFile none\n\
         Ciphers chacha20-poly1305@openssh.com\nKexAlgorithms curve25519-sha256\n\
         MACs hmac-sha2-256-etm@openssh.com\n",
    );
    // Only advertise sftp if the server binary exists and its path is metacharacter-free.
    if !sftp.is_empty() && !sftp.contains([' ', '\t', '\n', '"', '\'', '\\']) {
        cfg.push_str(&format!("Subsystem sftp {sftp}\n"));
    }
    if write_mode(CONFIG, cfg.as_bytes(), 0o600).is_err() {
        warn("cannot write sshd_config - SSH not started");
        return;
    }

    // 7. Lock the ssh dir read-only so nothing in the box can rewrite the config/keys after launch.
    if let Some(p) = cs(SSH_DIR) {
        unsafe {
            libc::mount(
                p.as_ptr(),
                p.as_ptr(),
                std::ptr::null(),
                libc::MS_BIND,
                std::ptr::null(),
            );
            libc::mount(
                std::ptr::null(),
                p.as_ptr(),
                std::ptr::null(),
                (libc::MS_REMOUNT | libc::MS_BIND | libc::MS_RDONLY) as libc::c_ulong,
                std::ptr::null(),
            );
        }
    }

    // 8. Locate sshd and fork it as a background child (foreground `-D` so it stays our child; it
    //    dies with the box's PID namespace). The parent returns to exec the box's PID 1.
    let sshd = ["/usr/sbin/sshd", "/usr/bin/sshd", "/sbin/sshd", "/bin/sshd"]
        .into_iter()
        .find(|p| Path::new(p).exists());
    let Some(sshd) = sshd else {
        warn("sshd not found - install openssh-server in the image (SSH not started)");
        return;
    };
    let pid = unsafe { libc::fork() };
    if pid < 0 {
        warn("fork for sshd failed - SSH not started");
        return;
    }
    if pid == 0 {
        use std::os::unix::process::CommandExt;
        let mut cmd = std::process::Command::new(sshd);
        cmd.args(["-D", "-f", CONFIG, "-e"]);
        cmd.env_clear();
        cmd.env(
            "PATH",
            "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        );
        if let Some(shim) = &preload {
            cmd.env("LD_PRELOAD", shim);
        }
        let _ = cmd.exec();
        std::process::exit(1);
    }
}

/// Compile the tiny setgroups/initgroups shim inside the box (matches the image's own libc - glibc or
/// musl - since it uses the box's compiler). Returns the `.so` path for `LD_PRELOAD`, or `None` when
/// no C compiler is available. The source is fixed and trusted; no untrusted input is compiled.
fn build_shim() -> Option<String> {
    let cc = ["cc", "gcc", "clang", "tcc", "musl-gcc"]
        .into_iter()
        .find(|c| which(c))?;
    let src = "/run/kern-ssh/nogroups.c";
    let code = b"int setgroups(unsigned long n, const void*l){(void)n;(void)l;return 0;}\n\
                 int initgroups(const char*u,unsigned int g){(void)u;(void)g;return 0;}\n";
    write_mode(src, code, 0o644).ok()?;
    let ok = std::process::Command::new(cc)
        .args(["-shared", "-fPIC", "-o", SHIM, src])
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    ok.then(|| SHIM.to_string())
}

fn which(bin: &str) -> bool {
    std::env::var("PATH")
        .unwrap_or_else(|_| "/usr/bin:/bin:/usr/local/bin".into())
        .split(':')
        .any(|d| !d.is_empty() && Path::new(d).join(bin).exists())
}

fn set_mode(path: &str, mode: u32) {
    use std::os::unix::fs::PermissionsExt;
    let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode));
}

fn write_mode(path: &str, bytes: &[u8], mode: u32) -> std::io::Result<()> {
    use std::os::unix::fs::OpenOptionsExt;
    let mut f = std::fs::OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(true)
        .mode(mode)
        .open(path)?;
    f.write_all(bytes)
}

fn bind_over(src: &str, dst: &str) {
    if let (Some(s), Some(d)) = (cs(src), cs(dst)) {
        unsafe {
            libc::mount(
                s.as_ptr(),
                d.as_ptr(),
                std::ptr::null(),
                libc::MS_BIND,
                std::ptr::null(),
            );
        }
    }
}

fn warn(msg: &str) {
    eprintln!("kern: warning: --ssh: {msg}");
}
